### PR TITLE
Fix - Values inside <> are missing on report portal web #3

### PR DESCRIPTION
**Pull request by shatulsky**
Fixes - https://github.com/reportportal/logger-net-log4net/issues/3
image

### CODE REVIEW

**Comment by nvborisenko** [comment]
The issue is not trivial. If we switch log view, we can see correct log message.

I verified your fix: markdown view shows message correctly, but plain view does not.

image

Since this switcher depends on user desires, I propose to make it configurable at least. User will choose whether to encode strings or not.

**Comment by shatulsky** [comment]
Is it expected behavior when values inside the diamond brackets are not displaying?

**Comment by nvborisenko** [comment]
From my point of view text should be displayed as is. I am user.

The question is where this issue should be resolved... If on client side, I propose to fix it on client (not only for log4net). We need discuss it with backend team.

**Review by HardNorth — COMMENTED** [review]
The request breaks ability to format output with HTML, so shouldn't be approved. See: https://github.com/reportportal/reportportal/issues/1305

**Pull request closed without merging**
